version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:10.2
    restart: always
    volumes:
      - ./data/postgres/10.2/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - ${POSTGRES_PORT}:5432
  mariadb:
    container_name: mariadb
    image: mariadb:10.2
    restart: always
    volumes:
      - ./data/mariadb/10.2:/var/lib/mysql
      - ./config/mariadb/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - ${MARIADB_PORT}:3306
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:6379
  nginx:
    container_name: nginx
    image: nginx:stable
    restart: always
    volumes:
      - ./data/nginx/html:/usr/share/nginx/html:ro
    ports:
      - ${NGINX_PORT}:80
  memcached:
    container_name: memcached
    image: memcached
    ports:
      - ${MEMCACHED_PORT}:11211
